
    # Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main


pool:
  vmImage: ubuntu-latest
  

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  - task: SonarCloudPrepare@1
  inputs:
  


- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: SonarCloudPublish@1
- task: SonarCloudAnalyze@1
  inputs:
    pollingTimeoutSec: '300'
